# Generated by Django 5.2.11 on 2026-03-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('room_type', models.CharField(choices=[('relax', 'Відпочинок/Перебування'), ('meeting', 'Переговорна кімната'), ('office', 'Офісне приміщення'), ('event', 'Приміщення для заходів'), ('studio', 'Фото/відео/аудіо студія')], default='meeting', max_length=20, verbose_name='Тип приміщення')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вмістимість')),
                ('room_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площа')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ціна за годину')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ціна за день')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Початок бронювання')),
                ('end_time', models.DateTimeField(verbose_name='Кінець бронювання')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='Приміщення')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Кондиціонер')),
                ('has_heating', models.BooleanField(default=False, verbose_name='Опалення')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Телевізор')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Кухня')),
                ('has_fridge', models.BooleanField(default=False, verbose_name='Холодильник')),
                ('has_shower', models.BooleanField(default=False, verbose_name='Душ')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bookings.room', verbose_name='Приміщення')),
            ],
        ),
    ]
