# Generated by Django 5.2.11 on 2026-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time'], 'verbose_name': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Приміщення'},
        ),
        migrations.AlterModelOptions(
            name='roomfeatures',
            options={'verbose_name': 'Характеристики приміщення'},
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='roomfeatures',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Паркінг'),
        ),
        migrations.AddField(
            model_name='roomfeatures',
            name='has_projector',
            field=models.BooleanField(default=False, verbose_name='Проєктор'),
        ),
        migrations.AddField(
            model_name='roomfeatures',
            name='has_whiteboard',
            field=models.BooleanField(default=False, verbose_name='Дошка'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за день (грн)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за годину (грн)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_area',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площа'),
        ),
    ]
