# Generated by Django 5.2.11 on 2026-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адреса'),
        ),
    ]
